import React from "react";
import headshot from "../assets/images/headshot.jpg"

const AboutMe = () => (
  <section className="about-me">
    <img src={headshot} alt="Headshot of Maxwell Hurst" className="headshot" />
    <h2>About Me</h2>
    <p>My mission is to create value for both consumers and businesses. I attended AC Reynolds High School where I was the Student Body President. Later, I pursued further studies at UNC-Chapel Hill with assured admission into Kenan-Flagler Business School, where I specialized in Entrepreneurship and attained a minor in Philosophy, Politics, and Economics. From 2021-2024, I had the pleasure of building EATS2SEATS, leading a team of 3000+ staffers across 12 states. Through my role at EATS2SEATS, I provided flexible and lucrative work opportunities to our staff, allowing them to earn supplemental income at times convenient for them. I have built or helped build many of our foundational operational processes, I helped manage client relationships, I acted as the Interim CTO for over a year while we built our admin portal and E2S Staff/Leaders Apps, I developed our "My Trainings" online training program, I built out our YouTube channel as both a operational & marketing tool, I built a sustainable payroll/invoicing department, I managed a team of 8 full-time and 15 part-time employees to facilitate administrative operations, and I coordinated with an international development firm on a project basis to build our tech. During my time at E2S, I lead or helped lead our operations, payroll, invoicing, HR, development, marketing, and full-time/part-time/intern teams. Through my experience at EATS2SEATS, I have gained invaluable business experience and knowledge. Currently, in my role as a Sales Development Representative at Bandwidth, I get to help connect businesses with voice, SMS, or 911 solutions that work for them and their consumers. I value the opportunity to learn at such an innovative and NC-HQd company, experience I believe will help me launch my own SaaS product one day. Overall, I aspire to build, create, innovate, and provide value for consumers and businesses. If you love what you do, you will never work a day in your life. I am thankful that is true for me, and I hope everyone gets to find value and joy in their work. I seek mentorship and partnerships in the business world and would love to connect with you!</p>
    </section>
);

export default AboutMe;